package utils

import (
	"crypto/rand"
	"fmt"
	"io"
	"strings"

	"github.com/isnlan/coral/pkg/logging"
)

var logger = logging.MustGetLogger("utils")

// 首字母大写
func FirstUpper(s string) string {
	return strings.ToUpper(s[:1]) + s[1:]
}

// GenerateBytesUUID returns a UUID based on RFC 4122 returning the generated bytes
func GenerateBytesUUID() []byte {
	uuid := make([]byte, 16)
	_, err := io.ReadFull(rand.Reader, uuid)
	if err != nil {
		panic(fmt.Sprintf("Error generating UUID: %s", err))
	}

	// variant bits; see section 4.1.1
	uuid[8] = uuid[8]&^0xc0 | 0x80

	// version 4 (pseudo-random); see section 4.1.3
	uuid[6] = uuid[6]&^0xf0 | 0x40

	return uuid
}
