// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FabricDigital struct {
	// 数字身份唯一标识
	Bduid string `protobuf:"bytes,1,opt,name=bduid,proto3" json:"bduid,omitempty"`
	// 区块链网络ID
	NetworkId string `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// 加密后的私钥
	PrivateKey string `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// 证书
	Cert string `protobuf:"bytes,4,opt,name=cert,proto3" json:"cert,omitempty"`
	// msp id
	MspId string `protobuf:"bytes,5,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	// 激活状态
	Status bool `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	// 是否是组织
	IsOrg                bool     `protobuf:"varint,7,opt,name=is_org,json=isOrg,proto3" json:"is_org,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FabricDigital) Reset()         { *m = FabricDigital{} }
func (m *FabricDigital) String() string { return proto.CompactTextString(m) }
func (*FabricDigital) ProtoMessage()    {}
func (*FabricDigital) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *FabricDigital) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FabricDigital.Unmarshal(m, b)
}
func (m *FabricDigital) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FabricDigital.Marshal(b, m, deterministic)
}
func (m *FabricDigital) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FabricDigital.Merge(m, src)
}
func (m *FabricDigital) XXX_Size() int {
	return xxx_messageInfo_FabricDigital.Size(m)
}
func (m *FabricDigital) XXX_DiscardUnknown() {
	xxx_messageInfo_FabricDigital.DiscardUnknown(m)
}

var xxx_messageInfo_FabricDigital proto.InternalMessageInfo

func (m *FabricDigital) GetBduid() string {
	if m != nil {
		return m.Bduid
	}
	return ""
}

func (m *FabricDigital) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *FabricDigital) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *FabricDigital) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func (m *FabricDigital) GetMspId() string {
	if m != nil {
		return m.MspId
	}
	return ""
}

func (m *FabricDigital) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *FabricDigital) GetIsOrg() bool {
	if m != nil {
		return m.IsOrg
	}
	return false
}

type KBaasDigital struct {
	// 数字身份唯一标识
	Bduid string `protobuf:"bytes,1,opt,name=bduid,proto3" json:"bduid,omitempty"`
	// 区块链网络ID
	NetworkId string `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// 加密后的私钥
	PrivateKey string `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// 公钥
	PublicKey string `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// 证书
	Cert string `protobuf:"bytes,5,opt,name=cert,proto3" json:"cert,omitempty"`
	// 激活状态
	Status               bool     `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KBaasDigital) Reset()         { *m = KBaasDigital{} }
func (m *KBaasDigital) String() string { return proto.CompactTextString(m) }
func (*KBaasDigital) ProtoMessage()    {}
func (*KBaasDigital) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *KBaasDigital) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KBaasDigital.Unmarshal(m, b)
}
func (m *KBaasDigital) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KBaasDigital.Marshal(b, m, deterministic)
}
func (m *KBaasDigital) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KBaasDigital.Merge(m, src)
}
func (m *KBaasDigital) XXX_Size() int {
	return xxx_messageInfo_KBaasDigital.Size(m)
}
func (m *KBaasDigital) XXX_DiscardUnknown() {
	xxx_messageInfo_KBaasDigital.DiscardUnknown(m)
}

var xxx_messageInfo_KBaasDigital proto.InternalMessageInfo

func (m *KBaasDigital) GetBduid() string {
	if m != nil {
		return m.Bduid
	}
	return ""
}

func (m *KBaasDigital) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *KBaasDigital) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *KBaasDigital) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *KBaasDigital) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func (m *KBaasDigital) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type DigitalIdentity struct {
	// ClientID
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// 数字身份唯一标识
	Bduid string `protobuf:"bytes,2,opt,name=bduid,proto3" json:"bduid,omitempty"`
	// 服务中心的数字身份地址
	Proxy string `protobuf:"bytes,3,opt,name=proxy,proto3" json:"proxy,omitempty"`
	// 访问的区块链网络ID
	NetworkId string `protobuf:"bytes,4,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// 数字身份
	//
	// Types that are valid to be assigned to Digital:
	//	*DigitalIdentity_Fabric
	//	*DigitalIdentity_Kbaas
	Digital              isDigitalIdentity_Digital `protobuf_oneof:"digital"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DigitalIdentity) Reset()         { *m = DigitalIdentity{} }
func (m *DigitalIdentity) String() string { return proto.CompactTextString(m) }
func (*DigitalIdentity) ProtoMessage()    {}
func (*DigitalIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *DigitalIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalIdentity.Unmarshal(m, b)
}
func (m *DigitalIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalIdentity.Marshal(b, m, deterministic)
}
func (m *DigitalIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalIdentity.Merge(m, src)
}
func (m *DigitalIdentity) XXX_Size() int {
	return xxx_messageInfo_DigitalIdentity.Size(m)
}
func (m *DigitalIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalIdentity proto.InternalMessageInfo

func (m *DigitalIdentity) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *DigitalIdentity) GetBduid() string {
	if m != nil {
		return m.Bduid
	}
	return ""
}

func (m *DigitalIdentity) GetProxy() string {
	if m != nil {
		return m.Proxy
	}
	return ""
}

func (m *DigitalIdentity) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

type isDigitalIdentity_Digital interface {
	isDigitalIdentity_Digital()
}

type DigitalIdentity_Fabric struct {
	Fabric *FabricDigital `protobuf:"bytes,5,opt,name=fabric,proto3,oneof"`
}

type DigitalIdentity_Kbaas struct {
	Kbaas *KBaasDigital `protobuf:"bytes,6,opt,name=kbaas,proto3,oneof"`
}

func (*DigitalIdentity_Fabric) isDigitalIdentity_Digital() {}

func (*DigitalIdentity_Kbaas) isDigitalIdentity_Digital() {}

func (m *DigitalIdentity) GetDigital() isDigitalIdentity_Digital {
	if m != nil {
		return m.Digital
	}
	return nil
}

func (m *DigitalIdentity) GetFabric() *FabricDigital {
	if x, ok := m.GetDigital().(*DigitalIdentity_Fabric); ok {
		return x.Fabric
	}
	return nil
}

func (m *DigitalIdentity) GetKbaas() *KBaasDigital {
	if x, ok := m.GetDigital().(*DigitalIdentity_Kbaas); ok {
		return x.Kbaas
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DigitalIdentity) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DigitalIdentity_Fabric)(nil),
		(*DigitalIdentity_Kbaas)(nil),
	}
}

type Block struct {
	// 当前块高度
	Number uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// 前块Hash
	PreviousHash []byte `protobuf:"bytes,2,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	// 当前块Hash
	Hash []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	// 数据Hash
	DataHash []byte `protobuf:"bytes,4,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	// 当前块中交易数量
	TransactionCount int32 `protobuf:"varint,5,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	// 链ID
	ChannelId string `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// 区块大小
	Size int32 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// 时间戳
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *Block) GetTransactionCount() int32 {
	if m != nil {
		return m.TransactionCount
	}
	return 0
}

func (m *Block) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *Block) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Block) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Transaction struct {
	// 交易ID
	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// 链ID
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// 块高度
	BlockNumber uint64 `protobuf:"varint,3,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	// 合约名称
	Contract string `protobuf:"bytes,4,opt,name=Contract,proto3" json:"Contract,omitempty"`
	// 数字身份
	Creator string `protobuf:"bytes,5,opt,name=Creator,proto3" json:"Creator,omitempty"`
	// 签名
	Sign string `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	// 交易类型
	TxType string `protobuf:"bytes,7,opt,name=TxType,proto3" json:"TxType,omitempty"`
	// 时间戳
	Timestamp *timestamp.Timestamp `protobuf:"bytes,8,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	// 交易状态
	ValidationCode string `protobuf:"bytes,9,opt,name=validation_code,json=validationCode,proto3" json:"validation_code,omitempty"`
	// 事件
	Event                *Event   `protobuf:"bytes,10,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *Transaction) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *Transaction) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Transaction) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Transaction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Transaction) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *Transaction) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

func (m *Transaction) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Transaction) GetValidationCode() string {
	if m != nil {
		return m.ValidationCode
	}
	return ""
}

func (m *Transaction) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type Event struct {
	// 合约名称
	Contract string `protobuf:"bytes,1,opt,name=Contract,proto3" json:"Contract,omitempty"`
	// 事件名称
	EventName string `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// 数据
	Value                []byte   `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Event) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Event) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Chain struct {
	// 框架id "fabric.."
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// 网络名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 创建账户
	Account string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// 共识算法
	Consensus string `protobuf:"bytes,4,opt,name=consensus,proto3" json:"consensus,omitempty"`
	// 节点数量
	NodeCount int32 `protobuf:"varint,5,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	// tls是否开启
	TlsEnabled           bool     `protobuf:"varint,6,opt,name=tls_enabled,json=tlsEnabled,proto3" json:"tls_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}

func (m *Chain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chain.Unmarshal(m, b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
}
func (m *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(m, src)
}
func (m *Chain) XXX_Size() int {
	return xxx_messageInfo_Chain.Size(m)
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *Chain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chain) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Chain) GetConsensus() string {
	if m != nil {
		return m.Consensus
	}
	return ""
}

func (m *Chain) GetNodeCount() int32 {
	if m != nil {
		return m.NodeCount
	}
	return 0
}

func (m *Chain) GetTlsEnabled() bool {
	if m != nil {
		return m.TlsEnabled
	}
	return false
}

type Channel struct {
	Chain                *Chain   `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetChain() *Chain {
	if m != nil {
		return m.Chain
	}
	return nil
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChainStatus struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainStatus) Reset()         { *m = ChainStatus{} }
func (m *ChainStatus) String() string { return proto.CompactTextString(m) }
func (*ChainStatus) ProtoMessage()    {}
func (*ChainStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{8}
}

func (m *ChainStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainStatus.Unmarshal(m, b)
}
func (m *ChainStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainStatus.Marshal(b, m, deterministic)
}
func (m *ChainStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainStatus.Merge(m, src)
}
func (m *ChainStatus) XXX_Size() int {
	return xxx_messageInfo_ChainStatus.Size(m)
}
func (m *ChainStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ChainStatus proto.InternalMessageInfo

func (m *ChainStatus) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Contract struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Args                 [][]byte `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{9}
}

func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contract) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Contract) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Contract) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Contract) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ChannelInfo struct {
	// 链ID
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// 当前块高度
	BlockNumber uint64 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// 总交易数量
	TotalTransactions uint64 `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	// 开始时间
	StartTime            uint64   `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInfo) Reset()         { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()    {}
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{10}
}

func (m *ChannelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInfo.Unmarshal(m, b)
}
func (m *ChannelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInfo.Marshal(b, m, deterministic)
}
func (m *ChannelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInfo.Merge(m, src)
}
func (m *ChannelInfo) XXX_Size() int {
	return xxx_messageInfo_ChannelInfo.Size(m)
}
func (m *ChannelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInfo proto.InternalMessageInfo

func (m *ChannelInfo) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *ChannelInfo) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *ChannelInfo) GetTotalTransactions() uint64 {
	if m != nil {
		return m.TotalTransactions
	}
	return 0
}

func (m *ChannelInfo) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

type TransactionResponse struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{11}
}

func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(m, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *TransactionResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Node struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime           int64    `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	HostIp               string   `protobuf:"bytes,5,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Cpu                  string   `protobuf:"bytes,7,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               string   `protobuf:"bytes,8,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{12}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Node) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetHostIp() string {
	if m != nil {
		return m.HostIp
	}
	return ""
}

func (m *Node) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Node) GetCpu() string {
	if m != nil {
		return m.Cpu
	}
	return ""
}

func (m *Node) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func init() {
	proto.RegisterType((*FabricDigital)(nil), "protos.FabricDigital")
	proto.RegisterType((*KBaasDigital)(nil), "protos.KBaasDigital")
	proto.RegisterType((*DigitalIdentity)(nil), "protos.DigitalIdentity")
	proto.RegisterType((*Block)(nil), "protos.Block")
	proto.RegisterType((*Transaction)(nil), "protos.Transaction")
	proto.RegisterType((*Event)(nil), "protos.Event")
	proto.RegisterType((*Chain)(nil), "protos.Chain")
	proto.RegisterType((*Channel)(nil), "protos.Channel")
	proto.RegisterType((*ChainStatus)(nil), "protos.ChainStatus")
	proto.RegisterType((*Contract)(nil), "protos.Contract")
	proto.RegisterType((*ChannelInfo)(nil), "protos.ChannelInfo")
	proto.RegisterType((*TransactionResponse)(nil), "protos.TransactionResponse")
	proto.RegisterType((*Node)(nil), "protos.Node")
}

func init() {
	proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8)
}

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 968 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x51, 0x8e, 0xe3, 0x44,
	0x10, 0x5d, 0x27, 0x76, 0x66, 0x5c, 0x99, 0x65, 0x77, 0x7b, 0x67, 0xc1, 0x1a, 0x18, 0xcd, 0xe0,
	0x15, 0x62, 0x25, 0x20, 0x23, 0x2d, 0x3f, 0x7c, 0xf1, 0x31, 0x61, 0xd1, 0x44, 0x2b, 0x0d, 0x92,
	0x89, 0x10, 0x7f, 0x56, 0xdb, 0xee, 0x49, 0xac, 0xb1, 0xdd, 0x96, 0xbb, 0x1d, 0x26, 0x5c, 0x82,
	0x13, 0x70, 0x06, 0x24, 0x0e, 0x00, 0x27, 0xe0, 0x14, 0x5c, 0x04, 0x55, 0x75, 0x3b, 0x71, 0xac,
	0xe5, 0x83, 0x0f, 0xbe, 0x52, 0xf5, 0xaa, 0xdc, 0xae, 0x7a, 0x55, 0xaf, 0x1d, 0x98, 0x96, 0x32,
	0x13, 0xc5, 0xac, 0x6e, 0xa4, 0x96, 0x6c, 0x42, 0x3f, 0xea, 0xec, 0x62, 0x25, 0xe5, 0xaa, 0x10,
	0x57, 0xe4, 0x26, 0xed, 0xdd, 0x95, 0xce, 0x4b, 0xa1, 0x34, 0x2f, 0x6b, 0x93, 0x18, 0xfe, 0xe9,
	0xc0, 0xe3, 0x6f, 0x79, 0xd2, 0xe4, 0xe9, 0x37, 0xf9, 0x2a, 0xd7, 0xbc, 0x60, 0xa7, 0xe0, 0x25,
	0x59, 0x9b, 0x67, 0x81, 0x73, 0xe9, 0xbc, 0xf2, 0x23, 0xe3, 0xb0, 0x73, 0x80, 0x4a, 0xe8, 0x9f,
	0x64, 0x73, 0x1f, 0xe7, 0x59, 0x30, 0xa2, 0x90, 0x6f, 0x91, 0x45, 0xc6, 0x2e, 0x60, 0x5a, 0x37,
	0xf9, 0x86, 0x6b, 0x11, 0xdf, 0x8b, 0x6d, 0x30, 0xa6, 0x38, 0x58, 0xe8, 0xad, 0xd8, 0x32, 0x06,
	0x6e, 0x2a, 0x1a, 0x1d, 0xb8, 0x14, 0x21, 0x9b, 0xbd, 0x80, 0x49, 0xa9, 0x6a, 0x3c, 0xcf, 0x33,
	0xaf, 0x2a, 0x55, 0xbd, 0xc8, 0xd8, 0xfb, 0x30, 0x51, 0x9a, 0xeb, 0x56, 0x05, 0x93, 0x4b, 0xe7,
	0xd5, 0x71, 0x64, 0x3d, 0x4c, 0xcf, 0x55, 0x2c, 0x9b, 0x55, 0x70, 0x44, 0xb8, 0x97, 0xab, 0xef,
	0x9a, 0x55, 0xf8, 0x9b, 0x03, 0x27, 0x6f, 0xaf, 0x39, 0x57, 0xff, 0x6f, 0x03, 0xe7, 0x00, 0x75,
	0x9b, 0x14, 0x79, 0x4a, 0x71, 0xd3, 0x86, 0x6f, 0x90, 0x7e, 0x7f, 0x5e, 0xaf, 0xbf, 0x7f, 0x69,
	0x24, 0xfc, 0xdb, 0x81, 0x27, 0xb6, 0xd8, 0x45, 0x26, 0x2a, 0x9d, 0xeb, 0x2d, 0xfb, 0x10, 0xfc,
	0xb4, 0xc8, 0x45, 0xa5, 0xe3, 0x5d, 0xe1, 0xc7, 0x06, 0x58, 0x64, 0xfb, 0x8e, 0x46, 0xfd, 0x8e,
	0x4e, 0xc1, 0xab, 0x1b, 0xf9, 0xd0, 0x15, 0x6b, 0x9c, 0x41, 0x9f, 0xee, 0xb0, 0xcf, 0x2b, 0x98,
	0xdc, 0xd1, 0xb8, 0xa9, 0xd2, 0xe9, 0xeb, 0x17, 0x66, 0x0f, 0xd4, 0xec, 0x60, 0x09, 0x6e, 0x1e,
	0x45, 0x36, 0x8d, 0x7d, 0x0e, 0xde, 0x7d, 0xc2, 0xb9, 0xe9, 0x61, 0xfa, 0xfa, 0xb4, 0xcb, 0xef,
	0x53, 0x7e, 0xf3, 0x28, 0x32, 0x49, 0xd7, 0x3e, 0x1c, 0x65, 0x06, 0x0b, 0x7f, 0x19, 0x81, 0x77,
	0x5d, 0xc8, 0xf4, 0x1e, 0x79, 0xa8, 0xda, 0x32, 0x11, 0x0d, 0x35, 0xe6, 0x46, 0xd6, 0x63, 0x2f,
	0xe1, 0x71, 0xdd, 0x88, 0x4d, 0x2e, 0x5b, 0x15, 0xaf, 0xb9, 0x5a, 0x53, 0x7b, 0x27, 0xd1, 0x49,
	0x07, 0xde, 0x70, 0xb5, 0x46, 0x62, 0x29, 0x36, 0xa6, 0x18, 0xd9, 0x48, 0x56, 0xc6, 0x35, 0x37,
	0x0f, 0xb9, 0x14, 0x38, 0x46, 0x80, 0x1e, 0xf8, 0x0c, 0x9e, 0xe9, 0x86, 0x57, 0x8a, 0xa7, 0x3a,
	0x97, 0x55, 0x9c, 0xca, 0xb6, 0x32, 0x63, 0xf1, 0xa2, 0xa7, 0xbd, 0xc0, 0x1c, 0x71, 0x64, 0x2b,
	0x5d, 0xf3, 0xaa, 0x12, 0x05, 0xb2, 0x35, 0x31, 0x6c, 0x59, 0x64, 0x91, 0xe1, 0xcb, 0x55, 0xfe,
	0xb3, 0xa0, 0x85, 0xf3, 0x22, 0xb2, 0xd9, 0x57, 0xe0, 0xef, 0x44, 0x14, 0x1c, 0x13, 0x29, 0x67,
	0x33, 0x23, 0xb3, 0x59, 0x27, 0xb3, 0xd9, 0xb2, 0xcb, 0x88, 0xf6, 0xc9, 0xe1, 0x5f, 0x23, 0x98,
	0x2e, 0xf7, 0x15, 0xb0, 0xe7, 0xe0, 0xe9, 0x87, 0xfd, 0xbc, 0x5d, 0xfd, 0xb0, 0xc8, 0x06, 0x15,
	0x8d, 0x86, 0x15, 0x5d, 0xc2, 0x94, 0x48, 0xbd, 0x35, 0x84, 0x8e, 0x89, 0xd0, 0x3e, 0xc4, 0xce,
	0xe0, 0x78, 0x2e, 0x2b, 0xdd, 0xf0, 0xb4, 0x53, 0xdb, 0xce, 0x67, 0x01, 0x1c, 0xcd, 0x1b, 0xc1,
	0xb5, 0x6c, 0xec, 0xa2, 0x76, 0xae, 0xe9, 0x74, 0x55, 0x59, 0x0a, 0xc8, 0xc6, 0xb9, 0x2d, 0x1f,
	0x96, 0xdb, 0xda, 0xf4, 0xef, 0x47, 0xd6, 0x43, 0x06, 0x96, 0xff, 0x85, 0x81, 0x9d, 0xc9, 0x3e,
	0x85, 0x27, 0x1b, 0x5e, 0xe4, 0x19, 0xb7, 0xa3, 0xc9, 0x44, 0xe0, 0xd3, 0xd1, 0xef, 0xed, 0xe1,
	0xb9, 0xcc, 0x04, 0x7b, 0x09, 0x9e, 0xd8, 0x88, 0x4a, 0x07, 0x40, 0xc7, 0x3f, 0xee, 0xb6, 0xee,
	0x0d, 0x82, 0x91, 0x89, 0x85, 0x3f, 0x82, 0x47, 0xfe, 0x41, 0xcb, 0xce, 0xa0, 0xe5, 0x73, 0x00,
	0xca, 0x8e, 0x2b, 0x5e, 0x8a, 0x8e, 0x4f, 0x42, 0x6e, 0x79, 0x29, 0x50, 0x44, 0x3f, 0xf0, 0xa2,
	0x15, 0x76, 0xbf, 0x8c, 0x13, 0xfe, 0xee, 0x80, 0x37, 0x5f, 0xf3, 0xbc, 0x1a, 0xc8, 0xc9, 0x19,
	0xca, 0x89, 0x81, 0xdb, 0x3b, 0x97, 0x6c, 0x24, 0x99, 0xa7, 0x66, 0xed, 0x8c, 0x32, 0x3b, 0x97,
	0x7d, 0x04, 0x7e, 0x2a, 0x2b, 0x25, 0x2a, 0xd5, 0xaa, 0x4e, 0x9a, 0x3b, 0x80, 0x5e, 0x25, 0x33,
	0x71, 0xb0, 0xb1, 0x3e, 0x22, 0x66, 0x55, 0x2f, 0x60, 0xaa, 0x0b, 0x15, 0x8b, 0x8a, 0x27, 0x85,
	0xc8, 0xec, 0x95, 0x02, 0xba, 0x50, 0x6f, 0x0c, 0x12, 0x5e, 0xc3, 0xd1, 0xdc, 0xec, 0x09, 0xd2,
	0x97, 0x62, 0xf9, 0x54, 0x70, 0x8f, 0x3e, 0xea, 0x29, 0x32, 0xb1, 0x77, 0xd5, 0x1e, 0x7e, 0x02,
	0x53, 0xca, 0xf9, 0xde, 0x5c, 0xb9, 0xfb, 0x1b, 0xcc, 0x39, 0xb8, 0xc1, 0xf4, 0x9e, 0xf0, 0xdd,
	0x31, 0x4e, 0x8f, 0x02, 0x06, 0x6e, 0xcd, 0xf5, 0xba, 0x3b, 0x1a, 0x6d, 0xa4, 0x65, 0x23, 0x1a,
	0x95, 0xcb, 0xaa, 0xa3, 0xc5, 0xba, 0x98, 0xcd, 0x9b, 0x15, 0x32, 0x32, 0x46, 0x89, 0xa3, 0x8d,
	0x18, 0x2a, 0x9a, 0x68, 0x38, 0x89, 0xc8, 0x0e, 0x7f, 0x75, 0xa8, 0x3a, 0x52, 0x42, 0x75, 0x27,
	0x07, 0x52, 0x71, 0x86, 0x52, 0xf9, 0x18, 0x4e, 0x12, 0xd4, 0x45, 0x6c, 0x2f, 0x9f, 0x91, 0xd1,
	0x4a, 0xd2, 0xd3, 0xca, 0x17, 0xc0, 0xb4, 0xd4, 0xbc, 0x88, 0x7b, 0x17, 0x83, 0xb2, 0xa2, 0x7a,
	0x46, 0x91, 0x9e, 0x5e, 0x69, 0x42, 0x4a, 0xf3, 0x46, 0xc7, 0xa8, 0x69, 0x1a, 0xa0, 0x1b, 0xf9,
	0x84, 0xe0, 0x8a, 0x87, 0x5f, 0xc3, 0xf3, 0x5e, 0x7a, 0x24, 0x54, 0x8d, 0xb3, 0x7d, 0xb7, 0xcc,
	0xbb, 0xfe, 0x46, 0xbd, 0xfe, 0xfe, 0x70, 0xc0, 0xbd, 0xc5, 0xed, 0x3f, 0xa4, 0xdd, 0xdf, 0x7d,
	0x01, 0x2f, 0x60, 0x9a, 0xa2, 0x5e, 0x85, 0x29, 0x00, 0x9f, 0x1d, 0x47, 0x60, 0x20, 0xac, 0x60,
	0x37, 0x8b, 0xf1, 0x60, 0x16, 0xd2, 0x7e, 0x79, 0xbd, 0x88, 0x6c, 0xf6, 0x01, 0x1c, 0xad, 0xa5,
	0xd2, 0x71, 0x5e, 0xdb, 0x7b, 0x60, 0x82, 0xee, 0xa2, 0xc6, 0x64, 0x8d, 0x82, 0xb7, 0xd7, 0x00,
	0xda, 0xec, 0x29, 0x8c, 0xd3, 0xba, 0xb5, 0x77, 0x00, 0x9a, 0x58, 0x5f, 0x29, 0x4a, 0xd9, 0x6c,
	0x49, 0xfd, 0x7e, 0x64, 0xbd, 0xc4, 0xfc, 0xeb, 0xf8, 0xf2, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xde, 0x3b, 0xbf, 0xc3, 0x8b, 0x08, 0x00, 0x00,
}
